---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: install redhat-lsb-core
      yum:
        name: "{{ item }}"
        disablerepo: RHEL7
      with_items:
        - redhat-lsb-core
        - epel-release
        - python-pip
    - name: add motd
      copy:
        src: motd
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
