---
# tasks file for drbd
- name: Import ELRepo public key
  shell: rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org --httpproxy proxy.det.nsw.edu.au --httpport 80
  ignore_errors: true

- name: Install ELRepo for RHEL7
  shell: rpm -Uvh https://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm --httpproxy proxy.det.nsw.edu.au --httpport 80
  ignore_errors: true

- name: Install DRBD 8.4 packages
  yum:
    name: "{{ drbd_packages }}"

- name: Create VG
  lvg:
    vg: "{{ item.name }}"
    pvs: "{{ item.physical_volumes }}"
  loop: "{{ drbd_volume_groups }}"  

- name: Create LVMs
  lvol:
    vg: "{{ item.0.name }}"
    lv: "{{ item.1.name }}"
    size: "{{ item.1.size }}" 
    resizefs: yes
  with_subelements:
    - "{{ drbd_volume_groups }}"
    - logical_volumes

- name: Create filesystems
  filesystem:
    dev: "/dev/{{ item.0.name }}/{{ item.1.name }}"
    fstype: "{{ item.1.fs_type }}"
    resizefs: no
  with_subelements:
    - "{{ drbd_volume_groups }}"
    - logical_volumes

- name: Create mount points
  file:
    path: "{{ item.1.mountpath }}"
    state: directory
  with_subelements:
    - "{{ drbd_volume_groups }}"
    - logical_volumes

- name: Mount LVMs
  mount:
    path: "{{ item.1.mountpath }}"
    src: "/dev/{{ item.0.name }}/{{ item.1.name }}"
    fstype: "{{ item.1.fs_type }}"
    state: mounted
  with_subelements:
    - "{{ drbd_volume_groups }}"
    - logical_volumes



