---
- hosts: all
  become: yes
  tasks:
    - name: create trinidad group
      group:
        name: trinidad
        state: present
        gid: 1001
    - name: create tabbies group
      group:
        name: tabbies
        state: present
    - name: add user tyrone to group trinidad
      user:
        name: tyrone
        group: trinidad
    - name: add user tyrone to groups
      user:
        name: tyrone
        groups: ['tabbies', 'tyrone', 'wheel']
